name: jx2_platform
description: Biblioteca de utilitários multiplataforma
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.1